export const RERANK_WEIGHTS = {
  VECTOR: 0.7,
  RECENCY: 0.2,
  IMPORTANCE: 0.1,
  PREFERENCE_BOOST: 0.1,
} as const;

export const FACT_SCORING_WEIGHTS = {
  SCORE: 0.8,
  CONFIDENCE: 0.2,
} as const;

export const FACT_CONFIDENCE = {
  BASE: 0.5,
  MIN: 0.1,
  MAX: 1.0,
  SHORT_PENALTY: 0.2,
  LONG_BOOST: 0.1,
  OPTIMAL_LENGTH_BOOST: 0.1,
  ENTITY_MAX_BOOST: 0.2,
  ENTITY_PER_BOOST: 0.05,
  COMPLETE_SENTENCE_BOOST: 0.1,
  HAS_NUMBERS_BOOST: 0.05,
} as const;

export const TEXT_LENGTH_THRESHOLDS = {
  ENTITY_EXTRACTION: 20,
  FACT_EXTRACTION: 50,
  SHORT_FACT: 10,
  LONG_FACT: 100,
  OPTIMAL_FACT_MIN: 20,
  OPTIMAL_FACT_MAX: 200,
} as const;

export const RETRIEVAL_LIMITS = {
  DEFAULT_TOP_K: 5,
  DEFAULT_HYBRID_TOP_K: 30,
  DEFAULT_FACTS_TOP_K: 10,
  DEFAULT_FACTS_ABOUT_ENTITY: 10,
  DEFAULT_TOOL_PATTERNS: 10,
  PATTERN_EXPANSION_FACTS: 50,
  PATTERN_EXPANSION_TOOLS: 20,
  PATTERN_EXPANSION_SEED_MESSAGES: 5,
  FAILED_SUCCESS_PATTERNS: 5,
  RELATED_ENTITIES: 20,
  HYBRID_FACTS_RATIO: 0.3,
  ARCHIVED_MEMORY_RATIO: 0.3,
  ARCHIVED_MEMORY_MAX_SESSIONS: 10,
} as const;

export const DEFAULT_IMPORTANCE = {
  MESSAGE: 0.5,
  TOOL_TRACKING: 0.6,
} as const;

export const DEFAULT_CONFIDENCE = {
  PREFERENCE: 1.0,
} as const;
